language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: CFJAWL7TzkFwdNm0Q330YWrcgz9oqLY4+rg2Np/I+r/XskwrNsyKHBKF7djonthQYLpmQWwoHhyjf0tjtAZOypLbGlU29o1w4wHHCSpRNX796hkINAmNMar4AcKD/nfl//cGZObtxarjHKbuJyjyHOM76wLWejMYADQV3nTIPfBNMJss0lWHKDJFhAjRfUot9kHAB879+GGGP1MojF3oN5gjKTvfLHLJKwjqv2ynxUIIP0CkBG6P6ngOR7gg1MBd/0QEdDOPAM0I55YJCU6FN6AlRYD3MciqMJIbgYqMQXZJV77jFklp2zWwJTiLilMmZfl3PROWj5hCKM+oECFNVR14HB3Eq3Ock3thGb2kN2UXhxOzVYuwvO/+Wxvep97Usd7LBbJKP0rCcaIjuFc51PqaiV1B760K7+dgOf+xapg54wLqoBpj8cCDnqQ1nZ/4aClGzjCAqantvY8KynNJtdVJOWpSnnTQJnIJ67Nrc4pyTHDOA5TjRfRXofg4z/IvGyWUi+gQ7RUWdtKF5xfQdW/AX+txtGFerKYDGnOdLU3S2DWvpS5ldcV9cTUjAT+4nQnbRVdML2JJW0OmFNEf8TnRWjt77cy6wuOnP2af30hdZ5yE+vKgb0vCsfVJVEZilHzndWQAtpc0ZTy0v1BWdWyJ0oSuDsND3D73MVmYM8s=
