language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  app: dream-walker
  api_key:
    secure: g521mNUuyvjNrdrF9Sue6z7dITqc6HCUCz8EYOryaZxWIx2HcIw6SUHRCkpuj/a7NpehWp9iK1DNiG6CXg6Q+T/1pf+MdiGiSbIK5e5RZ+BcuzHs+3yW3ufLfpguwPOxIcXZlyjPU0P4fMrSyUt92+Z3BhXl73GyVGQsTLzOFSdfKaOps+sQBXKgo4L1L3VtvavRznzljeqFLQKejthMxutgJUMgum98LaduoI0aamptS5AdQMiHdq0b5ChDXiBtKpcfH5RP1TrYI76fGKp2z3KPTW5JSpymKT4ul2ZUeHQQMMoXUmP1kHL3E80i9w2Vnp0QuqH11BOZI14U/yDaLXla3XC7q9N4vcEVqamoG/ieQ/T9GRfQXcg2+p3I31GkTL9MBmYjmbpIKpV+VAz2xgAJM01F7KVqUcMT07lJyw8woP30Z01K1qHPYpSEhBsp9zxiwTv1xzZOTqhkLaWDtQoaX9XIRCDdupF4FG2gs0T8IdpdfA7mZ4AZEc8SsemeTEYRuwgdVAeZYHHbhxWArNSVkcGkmBtvnA3as5eL5c7wkcszmZHy8MTpWTQQJsfWHcO2CGK5sUKgEuwga23XlVphdBiNlagg6tQTDoPb67itvUkKpXN0/BGis0tteoKMC0eLrxwTGMfhR/bsDzddKKU6m70eXL8YiXDzogohBAQ=
