language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  app: powerful-hollows-62040
  api_key:
    secure: JWq1Ly94LaSAnNZGy5QXN0JL+AuiQ8czin2k5OvskZYyVpDqLOiSA1rg6kbmT6GTRYuMyy2Hdt23BIRZfKFeyZqmpp2F3pVFksUzg8V0NLxo1qDtYO0LYPpLNRzcdiP/Ct6fYD9PxXKPLKEAk4D9GDS1YasnzM+NFmiSHxq++Z8W0KEMN0JHqX9GaecraspBFCn4V+2GIceZzQ6901yVBNigGoB5kJXnKqvi8/EBerGdNm+XjB+byub9dE16g2iHmiuEWux7Gv6/7V9MZWIk99VRTqbmFeuWDtspL1jZ1sCFBypnhUO2NnPAWT1Cto3HV8Yu6OeH1RD9qF5vnlrXnDe1a0gJ3IwZi6dFRajlzTrcT7sZpH2lIkrOPBjsSQpRYnvcrlTzch9TM3F3uXVMN9mW9UVhhBnyvg49KA2Q4MkjsJu40cqbzEd0ML2ZmJ64PQuhoJAu/ARK9n82S0FVCXfX/CA+g8PhNTtxdmrPOJ51m2C5lvfHHxV8e6kC0/9OjDbcQmaXhhZ0dtGLztjB9Oa7wcNUgIgJxPcAZaIcYV/bwFL9RxA9W9UhZUnnq5f7V/P4DAZ6oOW8JOxe35lpehrT7Gxpg4ld/0qo7JGiNM0E3OVkCobHaLtCmGiM4dpZudBJpuwnxRNKgASGH+at2XAqNSWuPolKoCjvea35wXA=
