language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  app: dream-walker
  api_key:
    secure: F7Bk310ADhLkNrivIH2dlAEQ0xz6sm8r8FJmyJ+co8BtHLT5ZCe4khJXiDioS6mUNalI211Pf2Fb68WccjUrQjPQc7Y88U1uTQ+TZvVJN9EQ/qmfotmsHJ0eePyrgcUhNNAYOIzgjcR08Q5p41cz6bqrmKG5qFwe9lB2CZoN4a44xCsh+UnJYTgRa5emY4WcjzkMwqxs4p6OVLvgaQYhEclRCEguvKuqsx3hu2FKV7wJHeOQ1wHKmy4n4bd9SJH9t8r6iPEV7Que2epgMxvMwFDA3vNEtv4UHJsUiLnKBgiBNlIYtq5JJONGBrMf5nL6WZhiYz/zixnlEBpt0uDRVSnuXdtAs8XZdaNyPBfFdKjz07Gb6YQHe2uBTUfzNWtkIugbZjufRYbkOsr2h/MO7RHQt2JrkWRiMSfsRrDESUkPVY9Gr6D9HZbfcCasyiJuRJI98+d7ILFi+nRIgyKFzpxDLeFUkktpyzs6hywPkpdVet03KyOtR+umQOTY2+TXzyif4CjsZkSCcYGWuaX0x4s2ATvz8DKamjvZjOsozqF+rrcYzfKGrK0FZseZDAk+7IygJ6cVc8h9RVuO/zwNAqkAc2tCKfqucXcn/m77AA1NzksnXuTf1CdwMTDYxyzfCqHq1DvJt6SG6hl0lsD+QPcExMDfE0rv8DecxtwYYrM=
