language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  app: dream-walker
  api_key:
    secure: Fc7D5tla3o3Y1lBfilfz0PWC4lotaVd09MauLra2KDai5oZfI9l0Lz6YRpRLVDud1O96DgybDqGi7MpW8a8gwpt5+9ph+yzm2VI/+atsbV+TS3t3m/NXKiPyMGhlaupWau2zEc5RWTEYomEdh63VAJhKHijBBqadzxnHE6gVC9HxmXmRgWgTGV/ZbZTvzH0u+Z1TiTOm8OKhKBaVdWvDvCFdIf4kolW5hokjq8iNkE0Ysy8DV/jLPV7X3HPGbkBLVOfb7GhfR8uEgmdFFoLIi69nPFOcnuLocNAFXauG3OlrS6IsjEQ+EPIVMdCt0TNNXOAsU0mSdCFqED/qdepVn7qqMcgh629Mp1Fh8/e30XYzL9lcx+tXbmaznHA4ug6bwA+OttyMO1IwVo0UKO8r1fQbHT3XVbRFe8OBS7LjPv8kh68CB6MBnLkuJp7mpwxKEXjevZtYuSApgQyolIYXxLz1ren4k+iln5EIRjeugBXfH+O5FPNZ5rYNyHGofmb+xuMKaF1jOrT1oQPoO3zldZEH4G7xZB7rAgCIq7quHz+0bro+rXWy5/ZKgbtRILPzmzPVJjgfwKQhGH7VbsET7pNqH+WrqPwn5womDpPiBwGcgC7elrdp8OwoGfjEi/+3SXulLwiC/wZH6fslT4KTqYcOOrGWqSFU6JxifoJ1CzY=
